CREATE TABLE IF NOT EXISTS brand
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brand_id    BIGINT                      NOT NULL,
    category_id BIGINT                      NOT NULL,
    price       BIGINT                      NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);